// Package digest builds and emails the weekly TradeNexus digest: a branded
// PDF with the top 5 most recently acquired mutual-fund positions and the
// top 5 promoter-buying stocks, sent to every signed-up user.
package digest

import (
	"bytes"
	"fmt"

	"github.com/go-pdf/fpdf"

	"tradenexus/internal/deals"
	"tradenexus/internal/promoter"
)

// Same brand palette used everywhere else this app generates a branded
// export (Insights/MutualFunds/PromoterBuying/IPO canvas cards) — kept
// consistent across every document TradeNexus produces, not just on-screen.
var (
	colBrand = [3]int{139, 139, 255} // #8b8bff
	colText  = [3]int{20, 22, 27}    // near-black, readable on white print
	colMuted = [3]int{125, 133, 144} // #7d8590
	colGreen = [3]int{30, 160, 100}  // darker than the on-screen #3ecf8e — prints better on white
	colRed   = [3]int{214, 60, 70}   // darker than the on-screen #f0616d
)

func setColor(pdf *fpdf.Fpdf, c [3]int) { pdf.SetTextColor(c[0], c[1], c[2]) }

// buildDigestPDF renders the two tables into a single-page (or overflow if
// data is unusually large) A4 PDF and returns the raw bytes, ready to
// attach to an email.
func buildDigestPDF(dateRange string, promoters []promoter.StockSummary, funds []deals.FundAcquisition) ([]byte, error) {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(16, 16, 16)
	pdf.AddPage()

	pdf.SetFont("Helvetica", "B", 14)
	setColor(pdf, colBrand)
	pdf.CellFormat(0, 8, ">_ TradeNexus", "", 1, "L", false, 0, "")

	pdf.SetFont("Helvetica", "B", 18)
	setColor(pdf, colText)
	pdf.CellFormat(0, 10, "Weekly Digest", "", 1, "L", false, 0, "")

	pdf.SetFont("Helvetica", "", 11)
	setColor(pdf, colMuted)
	pdf.CellFormat(0, 8, dateRange, "", 1, "L", false, 0, "")
	pdf.Ln(4)

	fundHeaders := []string{"Stock", "Fund", "Value Acquired", "Date"}
	fundWidths := []float64{32, 78, 40, 28}
	drawSectionHeader(pdf, "Top 5 Mutual Fund Acquisitions")
	drawTableHeader(pdf, fundHeaders, fundWidths)
	for _, f := range funds {
		drawRow(pdf, fundWidths, []cell{
			{f.Symbol, colText, "B"},
			{f.FundName, colText, ""},
			{fmtVal(f.BuyValue), colGreen, "B"},
			{f.LastDealDate.Format("02 Jan"), colMuted, ""},
		})
	}
	if len(funds) == 0 {
		drawEmptyRow(pdf, fundWidths, "No mutual fund acquisitions recorded this week.")
	}
	pdf.Ln(8)

	promHeaders := []string{"Stock", "Company", "Stake Move", "+Pts", "Date"}
	promWidths := []float64{32, 54, 44, 22, 26}
	drawSectionHeader(pdf, "Top 5 Promoter Buying")
	drawTableHeader(pdf, promHeaders, promWidths)
	for _, p := range promoters {
		move := fmt.Sprintf("%.2f%% -> %.2f%%", p.FirstPct, p.LatestPct)
		drawRow(pdf, promWidths, []cell{
			{p.Symbol, colText, "B"},
			{p.CompanyName, colText, ""},
			{move, colMuted, ""},
			{fmt.Sprintf("+%.2f", p.PointIncrease), colGreen, "B"},
			{p.LatestDate.Format("02 Jan"), colMuted, ""},
		})
	}
	if len(promoters) == 0 {
		drawEmptyRow(pdf, promWidths, "No promoter buying recorded this week.")
	}

	pdf.SetY(-20)
	pdf.SetFont("Helvetica", "", 9)
	setColor(pdf, colMuted)
	pdf.CellFormat(0, 8, "Generated by TradeNexus", "", 0, "L", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func drawSectionHeader(pdf *fpdf.Fpdf, title string) {
	pdf.SetFont("Helvetica", "B", 13)
	setColor(pdf, colText)
	pdf.CellFormat(0, 8, title, "", 1, "L", false, 0, "")
}

func drawTableHeader(pdf *fpdf.Fpdf, headers []string, widths []float64) {
	pdf.SetFont("Helvetica", "B", 9)
	setColor(pdf, colMuted)
	for i, h := range headers {
		pdf.CellFormat(widths[i], 7, h, "B", 0, "L", false, 0, "")
	}
	pdf.Ln(-1)
}

type cell struct {
	text  string
	color [3]int
	style string // "" or "B"
}

// drawRow draws one table row, shrinking any cell's text to fit its column
// width first — measured via the PDF's own font metrics (GetStringWidth),
// not a guessed character count, so a long company/fund name can never
// overflow into the next column regardless of font or string.
func drawRow(pdf *fpdf.Fpdf, widths []float64, cells []cell) {
	const cellPadding = 2 // mm, matches CellFormat's implicit left/right inset
	for i, c := range cells {
		pdf.SetFont("Helvetica", c.style, 10)
		setColor(pdf, c.color)
		pdf.CellFormat(widths[i], 8, fitWidth(pdf, c.text, widths[i]-cellPadding), "B", 0, "L", false, 0, "")
	}
	pdf.Ln(-1)
}

// fitWidth shortens s with a trailing "..." until it measures within
// maxWidth in the pdf's currently-set font. Must be called after SetFont.
// ASCII "..." rather than a "…" glyph — fpdf's core Helvetica font is
// cp1252-encoded, and U+2026 renders as mojibake without a font/encoding
// translation this doesn't otherwise need (same reason the app's PDF
// exports use "Rs." instead of "₹" elsewhere in this codebase).
func fitWidth(pdf *fpdf.Fpdf, s string, maxWidth float64) string {
	if pdf.GetStringWidth(s) <= maxWidth {
		return s
	}
	r := []rune(s)
	for len(r) > 1 {
		r = r[:len(r)-1]
		if pdf.GetStringWidth(string(r)+"...") <= maxWidth {
			return string(r) + "..."
		}
	}
	return string(r)
}

func drawEmptyRow(pdf *fpdf.Fpdf, widths []float64, msg string) {
	total := 0.0
	for _, w := range widths {
		total += w
	}
	pdf.SetFont("Helvetica", "", 10)
	setColor(pdf, colMuted)
	pdf.CellFormat(total, 8, msg, "B", 1, "L", false, 0, "")
}

// fmtVal mirrors the frontend's compact-rupee formatting (₹1.23 Cr / ₹45.6
// L) so the PDF reads the same as every on-screen value in the app.
func fmtVal(n float64) string {
	v := n
	if v < 0 {
		v = -v
	}
	switch {
	case v >= 1e7:
		return fmt.Sprintf("Rs.%.2f Cr", n/1e7)
	case v >= 1e5:
		return fmt.Sprintf("Rs.%.2f L", n/1e5)
	default:
		return fmt.Sprintf("Rs.%.0f", n)
	}
}
